version: 2.1

jobs:
    FBCWebTest:
         # The primary container is an instance of the first image listed. The job's commands run in this container.
        docker:
          - image: lssautomation/fbcweb:staging 
            name: automation_docker
        resource_class: medium
        steps:
          - run: sleep 30
          - run:
              name: Curl Version
              command: appropriate/curl --version
          - run:
              name: Add Run
              command: appropriate/curl -s --retry 3  'http://localhost:8080/AutomationServices/rs/as/add?LicenseKey=2MZS5YFLF6DP4C7RSCPX6NPMS7BXNODWUN83IBV04AQSVKGRMCDLOCALSTAGINGDB&Comments=CircleCI&WaitForRunToComplete=true&AbortRunOnScenarioFail=false&Tag=@Test_Set$smoke&BuildScriptApplication=CircleCI&TestData=TD_FBC_INVENTORY_URL:https://lodestone-automation-test.thesymphony.cloud,TD_USER1_EMAIL:test@prod.com,TD_USER1_PASS:test@prod.com&BuildScriptNumber='+$CIRCLE_BUILD_NUM    
workflows:
    "FBC Web Test Workflow":
        jobs:
           - FBCWebTest
