version: 2.1

jobs:
    FBCWebTest:
         # The primary container is an instance of the first image listed. The job's commands run in this container.
        docker:
          - image: lssautomation/fbcweb:staging 
          - docker_layer_caching: true
        resource_class: medium
        steps:
          #- setup_remote_docker
          # The secondary container run in a primary container.  
          #- run:          
           #   name: Start FBC Web Test Docker
           #   command: docker run -dit -p 4000:8080 --name=automation_docker lssautomation/fbcweb:staging 
                #docker run -d -p 4000:8080 --name=Automation_Docker lssautomation/fbcweb:staging
          - run: sleep 30
          - run:
              name: Add Run
              command: curl -O 'http://localhost:4000/AutomationServices/rs/as/add?LicenseKey=2MZS5YFLF6DP4C7RSCPX6NPMS7BXNODWUN83IBV04AQSVKGRMCDLOCALSTAGINGDB&Comments=CircleCI&WaitForRunToComplete=true&AbortRunOnScenarioFail=false&Tag=@Test_Set$smoke&BuildScriptApplication=CircleCI&TestData=TD_FBC_INVENTORY_URL:https://lodestone-automation-test.thesymphony.cloud,TD_USER1_EMAIL:test@prod.com,TD_USER1_PASS:test@prod.com&BuildScriptNumber='+$CIRCLE_BUILD_NUM
              no_output_timeout: 2h 
          - run: sleep 90 
workflows:
    "FBC Web Test Workflow":
        jobs:
           - FBCWebTest
    
