version: 2.1

jobs:
    FBCWebTest:
         # The primary container is an instance of the first image listed. The job's commands run in this container.
        machine: true
        steps:
          - run : |
            docker run -dit -p 4000:8080 --name=automation_docker lssautomation/fbcweb:staging 
            docker ps -all
            sleep 10
            curl --retry 10 --retry-delay 5 -v 'http://localhost:8080/AutomationServices/rs/as/add?LicenseKey=2MZS5YFLF6DP4C7RSCPX6NPMS7BXNODWUN83IBV04AQSVKGRMCDLOCALSTAGINGDB&Comments=CircleCI&WaitForRunToComplete=true&AbortRunOnScenarioFail=false&Tag=@Test_Set$smoke&BuildScriptApplication=CircleCI&TestData=TD_FBC_INVENTORY_URL:https://lodestone-automation-test.thesymphony.cloud,TD_USER1_EMAIL:test@prod.com,TD_USER1_PASS:test@prod.com&BuildScriptNumber='+$CIRCLE_BUILD_NUM    
workflows:
    "FBC Web Test Workflow":
        jobs:
           - FBCWebTest
